### ISSUE TITLE
Don't convert input to an array

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-settle#1]
https://github.com/sindresorhus/p-settle/blob/5533d855599609609b68ab267e00eed7d30b8d50/index.js#L3

The iterable should be used directly instead of converting to an array. It would have the benefit of better supporting generated sequences.

A pull request would be wonderful 🙌🌟
## 

Related: https://github.com/sindresorhus/p-map/issues/1

**Comment by sindresorhus** [comment]
// @parro-it In case you wanna give this a shot too. Should be pretty similar to your [`p-map` PR](https://github.com/sindresorhus/p-map/pull/2). 😁

**Comment by parro-it** [comment]
I'll be happy to try...
