### ISSUE TITLE
Variadic types

### ISSUE THREAD

**Issue by ValentinH** [sindresorhus/p-settle#12]
Today, the TS definition does not support having different type for each promise passed.

This is a known limitation in Typescript and there is a funny workaround that can be seen in the definition for `Promise.all()`: https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.promise.d.ts#L113

Would you accept a PR that would apply the same pattern in the `d.ts` file?

**Comment by sindresorhus** [comment]
Sure

**Comment by ValentinH** [comment]
While doing it I actually faced a bug also present in `Promise.all()`: https://github.com/microsoft/TypeScript/issues/33752

I'll see if the fix in the PR (https://github.com/microsoft/TypeScript/pull/33707/files) is also working for pSettle, if yes, I'll do the PR.

**Comment by ValentinH** [comment]
It is working 🎉 

```ts
type Awaited<T> = T extends undefined ? T : T extends PromiseLike<infer U> ? U : T
export function pSettle<T extends readonly any[]>(
  values: T,
  options?: pSettle.Options
): Promise<{ -readonly [P in keyof T]: PromiseResult<Awaited<T[P]>> }> // 
```

However, as the PR on TS is not fixed I don't know if this could lead to unexpected issues.
