### ISSUE TITLE
Add an option to change return type to PromiseSettledResult

### ISSUE THREAD

**Issue by tychenjiajun** [sindresorhus/p-settle#16]
See https://github.com/microsoft/TypeScript/blob/ea521d45e92ab45fd168aa8ea97bd6f3b8952307/src/lib/es2020.promise.d.ts

**Comment by sindresorhus** [comment]
Instead of just adding an option, how about we add a `status` property to the result? Then it should be structurally compatible with `PromiseSettledResult`.

**Comment by tychenjiajun** [comment]
> Instead of just adding an option, how about we add a `status` property to the result? Then it should be structurally compatible with `PromiseSettledResult`.

Sounds good

**Comment by tychenjiajun** [comment]
> Instead of just adding an option, how about we add a `status` property to the result? Then it should be structurally compatible with `PromiseSettledResult`.

Should we change p-reflect first?

**Comment by sindresorhus** [comment]
Yes

**Comment by ch-jobor** [comment]
### See [Update the version of p-reflect used #17](https://github.com/sindresorhus/p-settle/pull/17)
