### ISSUE TITLE
Q: Why did you not use Promise.all?

### ISSUE THREAD

**Issue by albertstill** [sindresorhus/p-settle#3]
Curious why you didn't use Promise.all in this library? The compatibilty is [there](http://node.green/#Promise).

e.g

```js
const wrappedPromises = promises.map(promise =>
  Promise.resolve(promise).then(
    val => ({ value }),
    err => ({ reason })
  )
);

return Promise.all(wrappedPromises);
```

**Comment by sindresorhus** [comment]
That's a very good question. I have no idea to be honest. This does indeed make the code a lot simpler. Thanks!
