### ISSUE TITLE
Concurrency is actually not managed

### ISSUE THREAD

**Issue by saibotsivad** [sindresorhus/p-settle#6]
From the example in the readme you have

```js
// ...
const files = [
	'a.txt',
	'b.txt' // Doesn't exist
].map(x => fs.readFile(x, 'utf8'));

pSettle(files).then(result => {
// ...
```

And in the code you have

```js
return Promise.all(iterable.map(item => pReflect(limit(() => item))))
```

But this doesn't actually manage concurrent promises, since to do so you would need

```diff
- return Promise.all(iterable.map(item => pReflect(limit(() => item))))
+ return Promise.all(iterable.map(item => pReflect(limit(() => item())))
```

So that the `item` function isn't executed immediately but is instead waits for promises to settle so that only a number of them execute at a time.

Looks like this was introduced with https://github.com/sindresorhus/p-settle/pull/5/files @tiagomapmarques

**Comment by saibotsivad** [comment]
I think any way this is addressed is probably a major version bump 😬 either dropping concurrency support (obviously a major bump) or changing p-settle to take constructor functions like p-all does (also a major bump).

**Comment by saibotsivad** [comment]
If concurrency support is kept, I would expect the readme example to look more like this:

```js
// ...
const files = [
	'a.txt',
	'b.txt' // Doesn't exist
].map(() => async file => fs.readFile(file, 'utf8'));

pSettle(files).then(result => {
// ...
```

**Comment by saibotsivad** [comment]
@sindresorhus If you want I can make a pull request to add tests and fix this, but I'm not sure which way you want to take it. Should concurrency be removed? Or should p-settle take constructor functions instead?

**Comment by sindresorhus** [comment]
Thanks for noticing this! The `concurrency` option should stay. It's very useful. I'm just thinking how we can preserve the option while still allowing to keep it simple when it's not needed.

Ideally it would support:

1. Array of promises. (`concurrency` option not allowed)
2. Array of functions that return promises. (`concurrency` option allowed)
3. Array of non-promises + mapper function. (`concurrency` option allowed) (Like [`p-map`](https://github.com/sindresorhus/p-map))

I'm just not sure how to model this in a user-friendly way. Thoughts?

**Comment by saibotsivad** [comment]
Supporting all those things sounds like it would complect the code a bit, but not be unreasonable.

I'll make a pull request and see what you think.

**Comment by saibotsivad** [comment]
@sindresorhus What do you think about the approach in https://github.com/sindresorhus/p-settle/pull/7 ? It covers the three cases you listed, and doesn't add too much complexity, I think.

**Comment by saibotsivad** [comment]
@sindresorhus @tiagomapmarques @BendingBender Looks like this is still an issue even after the switch to TypeScript.

Earlier I proposed #7 but it wasn't merged prior to the switch to TypeScript.

If you think that approach is good, I can update the PR to be TypeScript, if that would be helpful.

**Comment by saibotsivad** [comment]
It doesn't seem like @sindresorhus has time/interest in fixing it, so I'd advise using something else--forking and fixing the bug wouldn't be too hard, look at #7 for guidance.

**Comment by sindresorhus** [comment]
@tiagomapmarques FYI. Your https://github.com/sindresorhus/p-settle/commit/e63e5c0c54c0d780a9588f6bae3f5aa95fe84344 change never actually worked.
